# Generated by Django 4.0.1 on 2022-06-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productDetailsVehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ad_id', models.IntegerField(max_length=10)),
                ('Title', models.TextField(max_length=30)),
                ('Description', models.TextField(blank=True, max_length=100, null=True)),
                ('Price', models.IntegerField()),
                ('Location', models.TextField()),
                ('Date_Added', models.DateTimeField(auto_now_add=True)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
