# Generated by Django 4.0.1 on 2022-06-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetailsvehicles',
            name='Date_Added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
