# Generated by Django 4.0.1 on 2022-06-08 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_productdetailsvehicles_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetailsvehicles',
            name='Date_Added',
        ),
    ]
